### ISSUE TITLE
Adding favicon to webpages

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/web-design-2-independent-project#2]
Hi @hellachella and @jessjodoin,

I've been trying to add the favicon to all webpages and it's not working. I watched Thomas's video and tried following those steps but when I run it through Markbot I get error messages saying the favicon.ico and favicon-196.png files are missing or misspelled, so not sure what I can do to fix this. Any suggestions?

**Comment by JessJodoin** [comment]
Oh all the favicon flies (favicon.ico, favicon-196.png, and favicon-16.png) don't need to be inside the images folder, so just move them out into the main website folder (web-design-2-independent-project folder).
